stages:
  - docker
  - cache
  - test
  - deploy

variables:
  REGISTRY: registry.gitlab.com
  IMAGE: $REGISTRY/slozzer/babel
  DOCKER_DRIVER: overlay2
  SBT: sbt -v -sbt-launch-dir ./cache/launchers -Dsbt.global.base=./cache/sbt -Dsbt.boot.directory=./cache/boot -Dsbt.ivy.home=./cache/ivy -Dsbt.coursier.home=./cache/coursier -Dmode=strict

cache: &cache
  key: global
  paths:
    - ./cache/
    - ./**/target/
  policy: pull

docker:
  stage: docker
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker pull $IMAGE:latest || true
    - docker build --cache-from $IMAGE:latest --tag $IMAGE:latest .
    - docker push $IMAGE:latest
  cache: {}

dependencies:
  stage: cache
  image: $IMAGE:latest
  script: $SBT test:compile
  cache:
    <<: *cache
    policy: pull-push

formatting:
  stage: test
  image: $IMAGE:latest
  script: $SBT scalafmtCheckAll

unit tests:
  stage: test
  image: $IMAGE:latest
  script: $SBT test

documentation:
  stage: test
  image: $IMAGE:latest
  script:
    - $SBT -Dmode=tolerant documentation/paradox
    - mv ./modules/documentation/target/paradox/site/main/ ./website/
  artifacts:
    paths:
      - ./website/
    expire_in: 1 week

artifacts:
  stage: deploy
  image: $IMAGE:latest
  script: $SBT ci-release
  only:
    - master
    - tags

pages:
  stage: deploy
  script:
    - mv ./website/ ./public/
  dependencies:
    - documentation
  artifacts:
    paths:
      - ./public/
  only:
    - tags