version: 2
jobs:
  build:
    working_directory: /lokal/
    docker:
      - image: openjdk:8
    environment:
      SBT_GHPAGES_COMMIT_MESSAGE: "Update site [ci skip]"
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "./build.sbt" }}-{{ checksum "./project/build.properties" }}-{{ checksum "./project/plugins.sbt" }}
      - run:
          name: Download dependencies
          command: |
            apt-get update
            curl -sL https://deb.nodesource.com/setup_8.x | bash
            apt-get install -y jekyll nodejs
            curl -Ls https://git.io/sbt > /bin/sbt && chmod 0755 /bin/sbt
      - run:
          name: Cache software dependencies
          command: |
            sbt -v coverage +test:update documentation/makeMicrosite
      - save_cache:
          paths:
            - ~/.apt-cache/
            - ~/.cache/
            - ~/.sbt/
            - ~/.ivy2/
          key: cache-{{ checksum "./build.sbt" }}-{{ checksum "./project/build.properties" }}-{{ checksum "./project/plugins.sbt" }}
      - run:
          name: Run tests
          command: |
            sbt -v clean coverage +test documentation/makeMicrosite coverageReport
      - run:
          name: Publish codecov
          command: |
            bash <(curl -s https://codecov.io/bash)
      - run:
          name: Publish microsite
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then ./scripts/publish-microsite.sh; fi