package io.taig.lokal

case class Country( value: String ) extends AnyVal

/**
 * Predefined countries, represented by their ISO 3166-2 codes
 *
 * @see http://data.okfn.org/data/core/country-list
 */
object Country {
    val AD = Country( "AD" ) // Andorra
    val AE = Country( "AE" ) // United Arab Emirates
    val AG = Country( "AG" ) // Antigua and Barbuda
    val AI = Country( "AI" ) // Anguilla
    val AL = Country( "AL" ) // Albania
    val AM = Country( "AM" ) // Armenia
    val AO = Country( "AO" ) // Angola
    val AQ = Country( "AQ" ) // Antarctica
    val AR = Country( "AR" ) // Argentina
    val AS = Country( "AS" ) // American Samoa
    val AT = Country( "AT" ) // Austria
    val AU = Country( "AU" ) // Australia
    val AW = Country( "AW" ) // Aruba
    val AX = Country( "AX" ) // Åland Islands
    val AZ = Country( "AZ" ) // Azerbaijan
    val BA = Country( "BA" ) // Bosnia and Herzegovina
    val BB = Country( "BB" ) // Barbados
    val BD = Country( "BD" ) // Bangladesh
    val BE = Country( "BE" ) // Belgium
    val BF = Country( "BF" ) // Burkina Faso
    val BG = Country( "BG" ) // Bulgaria
    val BH = Country( "BH" ) // Bahrain
    val BI = Country( "BI" ) // Burundi
    val BJ = Country( "BJ" ) // Benin
    val BL = Country( "BL" ) // Saint Barthélemy
    val BM = Country( "BM" ) // Bermuda
    val BN = Country( "BN" ) // Brunei Darussalam
    val BO = Country( "BO" ) // "Bolivia, Plurinational State of"
    val BQ = Country( "BQ" ) // "Bonaire, Sint Eustatius and Saba"
    val BR = Country( "BR" ) // Brazil
    val BS = Country( "BS" ) // Bahamas
    val BT = Country( "BT" ) // Bhutan
    val BV = Country( "BV" ) // Bouvet Island
    val BW = Country( "BW" ) // Botswana
    val BY = Country( "BY" ) // Belarus
    val BZ = Country( "BZ" ) // Belize
    val CA = Country( "CA" ) // Canada
    val CC = Country( "CC" ) // Cocos (Keeling) Islands
    val CD = Country( "CD" ) // "Congo, the Democratic Republic of the"
    val CF = Country( "CF" ) // Central African Republic
    val CG = Country( "CG" ) // Congo
    val CH = Country( "CH" ) // Switzerland
    val CI = Country( "CI" ) // Côte d'Ivoire
    val CK = Country( "CK" ) // Cook Islands
    val CL = Country( "CL" ) // Chile
    val CM = Country( "CM" ) // Cameroon
    val CN = Country( "CN" ) // China
    val CO = Country( "CO" ) // Colombia
    val CR = Country( "CR" ) // Costa Rica
    val CU = Country( "CU" ) // Cuba
    val CV = Country( "CV" ) // Cape Verde
    val CW = Country( "CW" ) // Curaçao
    val CX = Country( "CX" ) // Christmas Island
    val CY = Country( "CY" ) // Cyprus
    val CZ = Country( "CZ" ) // Czech Republic
    val DE = Country( "DE" ) // Germany
    val DJ = Country( "DJ" ) // Djibouti
    val DK = Country( "DK" ) // Denmark
    val DM = Country( "DM" ) // Dominica
    val DO = Country( "DO" ) // Dominican Republic
    val DZ = Country( "DZ" ) // Algeria
    val EC = Country( "EC" ) // Ecuador
    val EE = Country( "EE" ) // Estonia
    val EG = Country( "EG" ) // Egypt
    val EH = Country( "EH" ) // Western Sahara
    val ER = Country( "ER" ) // Eritrea
    val ES = Country( "ES" ) // Spain
    val ET = Country( "ET" ) // Ethiopia
    val FI = Country( "FI" ) // Finland
    val FJ = Country( "FJ" ) // Fiji
    val FK = Country( "FK" ) // Falkland Islands (Malvinas)
    val FM = Country( "FM" ) // "Micronesia, Federated States of"
    val FO = Country( "FO" ) // Faroe Islands
    val FR = Country( "FR" ) // France
    val GA = Country( "GA" ) // Gabon
    val GB = Country( "GB" ) // United Kingdom
    val GD = Country( "GD" ) // Grenada
    val GE = Country( "GE" ) // Georgia
    val GF = Country( "GF" ) // French Guiana
    val GG = Country( "GG" ) // Guernsey
    val GH = Country( "GH" ) // Ghana
    val GI = Country( "GI" ) // Gibraltar
    val GL = Country( "GL" ) // Greenland
    val GM = Country( "GM" ) // Gambia
    val GN = Country( "GN" ) // Guinea
    val GP = Country( "GP" ) // Guadeloupe
    val GQ = Country( "GQ" ) // Equatorial Guinea
    val GR = Country( "GR" ) // Greece
    val GS = Country( "GS" ) // South Georgia and the South Sandwich Islands
    val GT = Country( "GT" ) // Guatemala
    val GU = Country( "GU" ) // Guam
    val GW = Country( "GW" ) // Guinea-Bissau
    val GY = Country( "GY" ) // Guyana
    val HK = Country( "HK" ) // Hong Kong
    val HM = Country( "HM" ) // Heard Island and McDonald Islands
    val HN = Country( "HN" ) // Honduras
    val HR = Country( "HR" ) // Croatia
    val HT = Country( "HT" ) // Haiti
    val HU = Country( "HU" ) // Hungary
    val ID = Country( "ID" ) // Indonesia
    val IE = Country( "IE" ) // Ireland
    val IL = Country( "IL" ) // Israel
    val IM = Country( "IM" ) // Isle of Man
    val IN = Country( "IN" ) // India
    val IO = Country( "IO" ) // British Indian Ocean Territory
    val IQ = Country( "IQ" ) // Iraq
    val IR = Country( "IR" ) // "Iran, Islamic Republic of"
    val IS = Country( "IS" ) // Iceland
    val IT = Country( "IT" ) // Italy
    val JE = Country( "JE" ) // Jersey
    val JM = Country( "JM" ) // Jamaica
    val JO = Country( "JO" ) // Jordan
    val JP = Country( "JP" ) // Japan
    val KE = Country( "KE" ) // Kenya
    val KG = Country( "KG" ) // Kyrgyzstan
    val KH = Country( "KH" ) // Cambodia
    val KI = Country( "KI" ) // Kiribati
    val KM = Country( "KM" ) // Comoros
    val KN = Country( "KN" ) // Saint Kitts and Nevis
    val KP = Country( "KP" ) // "Korea, Democratic People's Republic of"
    val KR = Country( "KR" ) // "Korea, Republic of"
    val KW = Country( "KW" ) // Kuwait
    val KY = Country( "KY" ) // Cayman Islands
    val KZ = Country( "KZ" ) // Kazakhstan
    val LA = Country( "LA" ) // Lao People's Democratic Republic
    val LB = Country( "LB" ) // Lebanon
    val LC = Country( "LC" ) // Saint Lucia
    val LI = Country( "LI" ) // Liechtenstein
    val LK = Country( "LK" ) // Sri Lanka
    val LR = Country( "LR" ) // Liberia
    val LS = Country( "LS" ) // Lesotho
    val LT = Country( "LT" ) // Lithuania
    val LU = Country( "LU" ) // Luxembourg
    val LV = Country( "LV" ) // Latvia
    val LY = Country( "LY" ) // Libya
    val MA = Country( "MA" ) // Morocco
    val MC = Country( "MC" ) // Monaco
    val MD = Country( "MD" ) // "Moldova, Republic of"
    val ME = Country( "ME" ) // Montenegro
    val MF = Country( "MF" ) // Saint Martin (French part)
    val MG = Country( "MG" ) // Madagascar
    val MH = Country( "MH" ) // Marshall Islands
    val MK = Country( "MK" ) // "Macedonia, the Former Yugoslav Republic of"
    val ML = Country( "ML" ) // Mali
    val MM = Country( "MM" ) // Myanmar
    val MN = Country( "MN" ) // Mongolia
    val MO = Country( "MO" ) // Macao
    val MP = Country( "MP" ) // Northern Mariana Islands
    val MQ = Country( "MQ" ) // Martinique
    val MR = Country( "MR" ) // Mauritania
    val MS = Country( "MS" ) // Montserrat
    val MT = Country( "MT" ) // Malta
    val MU = Country( "MU" ) // Mauritius
    val MV = Country( "MV" ) // Maldives
    val MW = Country( "MW" ) // Malawi
    val MX = Country( "MX" ) // Mexico
    val MY = Country( "MY" ) // Malaysia
    val MZ = Country( "MZ" ) // Mozambique
    val NA = Country( "NA" ) // Namibia
    val NC = Country( "NC" ) // New Caledonia
    val NE = Country( "NE" ) // Niger
    val NF = Country( "NF" ) // Norfolk Island
    val NG = Country( "NG" ) // Nigeria
    val NI = Country( "NI" ) // Nicaragua
    val NL = Country( "NL" ) // Netherlands
    val NO = Country( "NO" ) // Norway
    val NP = Country( "NP" ) // Nepal
    val NR = Country( "NR" ) // Nauru
    val NU = Country( "NU" ) // Niue
    val NZ = Country( "NZ" ) // New Zealand
    val OM = Country( "OM" ) // Oman
    val PA = Country( "PA" ) // Panama
    val PE = Country( "PE" ) // Peru
    val PF = Country( "PF" ) // French Polynesia
    val PG = Country( "PG" ) // Papua New Guinea
    val PH = Country( "PH" ) // Philippines
    val PK = Country( "PK" ) // Pakistan
    val PL = Country( "PL" ) // Poland
    val PM = Country( "PM" ) // Saint Pierre and Miquelon
    val PN = Country( "PN" ) // Pitcairn
    val PR = Country( "PR" ) // Puerto Rico
    val PS = Country( "PS" ) // "Palestine, State of"
    val PT = Country( "PT" ) // Portugal
    val PW = Country( "PW" ) // Palau
    val PY = Country( "PY" ) // Paraguay
    val QA = Country( "QA" ) // Qatar
    val RE = Country( "RE" ) // Réunion
    val RO = Country( "RO" ) // Romania
    val RS = Country( "RS" ) // Serbia
    val RU = Country( "RU" ) // Russian Federation
    val RW = Country( "RW" ) // Rwanda
    val SA = Country( "SA" ) // Saudi Arabia
    val SB = Country( "SB" ) // Solomon Islands
    val SC = Country( "SC" ) // Seychelles
    val SD = Country( "SD" ) // Sudan
    val SE = Country( "SE" ) // Sweden
    val SG = Country( "SG" ) // Singapore
    val SH = Country( "SH" ) // "Saint Helena, Ascension and Tristan da Cunha"
    val SI = Country( "SI" ) // Slovenia
    val SJ = Country( "SJ" ) // Svalbard and Jan Mayen
    val SK = Country( "SK" ) // Slovakia
    val SL = Country( "SL" ) // Sierra Leone
    val SM = Country( "SM" ) // San Marino
    val SN = Country( "SN" ) // Senegal
    val SO = Country( "SO" ) // Somalia
    val SR = Country( "SR" ) // Suriname
    val SS = Country( "SS" ) // South Sudan
    val ST = Country( "ST" ) // Sao Tome and Principe
    val SV = Country( "SV" ) // El Salvador
    val SX = Country( "SX" ) // Sint Maarten (Dutch part)
    val SY = Country( "SY" ) // Syrian Arab Republic
    val SZ = Country( "SZ" ) // Swaziland
    val TC = Country( "TC" ) // Turks and Caicos Islands
    val TD = Country( "TD" ) // Chad
    val TF = Country( "TF" ) // French Southern Territories
    val TG = Country( "TG" ) // Togo
    val TH = Country( "TH" ) // Thailand
    val TJ = Country( "TJ" ) // Tajikistan
    val TK = Country( "TK" ) // Tokelau
    val TL = Country( "TL" ) // Timor-Leste
    val TM = Country( "TM" ) // Turkmenistan
    val TN = Country( "TN" ) // Tunisia
    val TO = Country( "TO" ) // Tonga
    val TR = Country( "TR" ) // Turkey
    val TT = Country( "TT" ) // Trinidad and Tobago
    val TV = Country( "TV" ) // Tuvalu
    val TW = Country( "TW" ) // "Taiwan, Province of China"
    val TZ = Country( "TZ" ) // "Tanzania, United Republic of"
    val UA = Country( "UA" ) // Ukraine
    val UG = Country( "UG" ) // Uganda
    val UM = Country( "UM" ) // United States Minor Outlying Islands
    val US = Country( "US" ) // United States
    val UY = Country( "UY" ) // Uruguay
    val UZ = Country( "UZ" ) // Uzbekistan
    val VA = Country( "VA" ) // Holy See (Vatican City State)
    val VC = Country( "VC" ) // Saint Vincent and the Grenadines
    val VE = Country( "VE" ) // "Venezuela, Bolivarian Republic of"
    val VG = Country( "VG" ) // "Virgin Islands, British"
    val VI = Country( "VI" ) // "Virgin Islands, U.S."
    val VN = Country( "VN" ) // Viet Nam
    val VU = Country( "VU" ) // Vanuatu
    val WF = Country( "WF" ) // Wallis and Futuna
    val WS = Country( "WS" ) // Samoa
    val YE = Country( "YE" ) // Yemen
    val YT = Country( "YT" ) // Mayotte
    val ZA = Country( "ZA" ) // South Africa
    val ZM = Country( "ZM" ) // Zambia
    val ZW = Country( "ZW" ) // Zimbabwe
    val AF = Country( "AF" ) // Afghanistan
}